
#define IDLE_TICK_INTERVAL 2000
#define IDLE_TICK_FREQUENCY 262
#define IDLE_ACCELERATION_THRESHOLD 10
#define IDLE_ALTITUDE_THRESHOLD 6

#define ASCENDING_TICK_INTERVAL 2000
#define ASCENDING_TICK_FREQUENCY_A 250
#define ASCENDING_TICK_FREQUENCY_B 350
#define ASCTODES_ACCELERATION_THRESHOLD 0

#define DEPLOY_ALTITUDE_THRESHOLD 400

#define DEFAULT_SERVO_POSITION 0
#define DEPLOY_SERVO_POSITION 90

#define ACCELERATION_N_SAMPLES 100
#define ALTITUDE_N_SAMPLES 100

#define GROUNDED_ACCELERATION 0.5f
